### ISSUE TITLE
Problem installing guess-language-spirit

### ISSUE THREAD

**Issue by kamaxeon** [miguelgrinberg/microblog#71] opened 2018-01-16 12:28 UTC
Hi @miguelgrinberg,

First, I would like to say thanks to you for your work. I'm reading and typing your project. 

Now, I'm on chapter 14, and I can't install guess_language-spirit (with pipenv or pip)

```
(flask_mega_tutorial-x-oOu59U) ➜  flask_mega_tutorial git:(master) pipenv install guess_language-spirit
Installing guess_language-spirit…
Collecting guess_language-spirit

Error:  An error occurred while installing guess_language-spirit!
  Could not find a version that satisfies the requirement guess_language-spirit (from versions: )
No matching distribution found for guess_language-spirit

(flask_mega_tutorial-x-oOu59U) ➜  flask_mega_tutorial git:(master) pip install guess_language-spirit
Collecting guess_language-spirit
  Could not find a version that satisfies the requirement guess_language-spirit (from versions: )
No matching distribution found for guess_language-spirit
```

My python version is 3.6.4. My solution has been downloading the package (tar.gz) and installs it manually.

Have you any idea?

**Comment by miguelgrinberg** [comment] 2018-01-16 17:55
Not sure. This is working for me, and I can see the package listed on the pypi site: https://pypi.python.org/pypi/guess_language-spirit. Maybe a temporary hiccup?

**Comment by JaviKx2** [comment] 2018-03-16 09:04
Hi, 

Same thing is happening to me!

I noticed the name of the lib in requirements.txt has no underscore, but It didn't work either

requirements.txt:
...
guess-language-spirit==0.5.3
...

Shouldn't it be 'guess_language-spirit==0.5.3'?

**Comment by miguelgrinberg** [comment] 2018-03-16 15:52
Oh yeah, so sorry about that! It's now fixed.

**Closed by miguelgrinberg** 2018-03-16 15:52 UTC
Labels: question

**Comment by Xerrex** [comment] 2018-06-01 07:19
Hello everyone. I know the issue is closed but I had trouble installing the package and resulted in installing it manually

**Comment by Xerrex** [comment] 2018-06-02 08:26
Hi everyone i still cannot install guess_language-spirit.
**Could not find a version that satisfies the requirement guess_language-spirit (from versions: )
No matching distribution found for guess_language-spirit**

**Comment by miguelgrinberg** [comment] 2018-06-02 13:52
@Xerrex My guess is that it was a temporary problem. I just verified that the guess_language-spirit package is still available on PyPI. Maybe PyPI was temporarily down when you tried, or your network was down. Give it another try, I just tested it here and it installs fine.

**Comment by Xerrex** [comment] 2018-07-11 09:47
@miguelgrinberg Will keep trying but it has just failed. I ran **pip install guess_language-spirit** from [here](https://pypi.org/project/guess_language-spirit/)

**Comment by marlonschroder** [comment] 2018-07-11 14:29
Try install enchant before pip install:

apt-get install python3-enchant

**Comment by miguelgrinberg** [comment] 2018-09-08 22:40
@neo1691 I'll fix it, thanks!

**Comment by Xerrex** [comment] 2018-10-16 15:11
:face_with_head_bandage: I still have not managed to install that guess_language-spirit am using 
python 3.6.4

**Comment by WaterDropTec** [comment] 2018-10-20 11:36
I can install  guess_language-spirit without any error. But when I run Flask run, I got a SyntaxError: invalid syntax, which is "from guess_language-spirit import guess_language". It seems like it is illegal to use "-" in "language-spirit".
someone known why?thanks

**Comment by imbyron** [comment] 2018-11-22 13:51
Could not find a version that satisfies the requirement guess_language-spirit==0.5.3 (from -r requirements.txt (line 18)) (from versions: )
No matching distribution found for guess_language-spirit==0.5.3 (from -r requirements.txt (line 18))

**Comment by imbyron** [comment] 2018-11-22 13:52
i still cannot install guess_language-spirit.

**Comment by miguelgrinberg** [comment] 2018-11-22 16:16
@imbyron the problem has to be on your side, I see version 0.5.3 in pypi: https://pypi.org/project/guess_language-spirit/0.5.3/

**Comment by sophyphreak** [comment] 2019-08-23 05:25
I'm also getting this error, but I'm doing the tutorial using `pipenv` instead of the instructed virtual environment. Not sure if that makes a difference.
```
ERROR: ERROR: Could not find a version that matches guess-language-spirit
No versions found
```

**Comment by miguelgrinberg** [comment] 2019-08-23 08:29
@sophyphreak this package has a tricky name, `guess_language-spirit`. Note that the first separator is an underscore, the second a hyphen. You used hyphens for both.

**Comment by sophyphreak** [comment] 2019-08-25 02:30
@miguelgrinberg I'm very sorry to contradict you, but whenever I run either `pipenv install guess_language-spirit` or `pipenv install guess-language_spirit` (the second is what is in the paper version of you very good book (which I'm very grateful you wrote)) whenever I wrun either od those scripts, it gets saved in my pipenv file as `guess-language-spirit ` and I don't know why. I'm not saying I'm not doing anything wrong, but if I'm doing something wrong, it's not that. (Again, thank you a lot for writing the book and keeping up with these github issues.)

**Comment by miguelgrinberg** [comment] 2019-08-25 08:48
@sophyphreak sorry, the package name is `guess-language_spirit`, it is the second separator that is an underscore, my bad. You can see this package in its PyPI page at https://pypi.org/project/guess_language-spirit/.

I don't use pipenv so I'm not super experienced with it, but after a quick test I can confirm that the package appears with two hyphens in the pipfile. But regardless of that, it installs and works fine.

```
(venv) $ pipenv install guess-language_spirit
Creating a Pipfile for this project…
Installing guess-language_spirit…
Adding guess-language_spirit to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (9858d5)!
Installing dependencies from Pipfile.lock (9858d5)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
(venv) $ cat Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
guess-language-spirit = "*"

[requires]
python_version = "3.7"
```
